#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$WORKSPACE_DIR"

TMP_DIR=".wrangler/tmp"
TMP_FILE="$TMP_DIR/worker-configuration.check.d.ts"

cleanup() {
  rm -f "$TMP_FILE"
}

trap cleanup EXIT

mkdir -p "$TMP_DIR"

echo "[types-check] Generating temporary Wrangler types for comparison"
npx wrangler types "$TMP_FILE" >/dev/null

normalize_types() {
  python3 - "$1" <<'PY'
from pathlib import Path
import re
import sys

text = Path(sys.argv[1]).read_text()
text = re.sub(
    r"// Generated by Wrangler by running `wrangler types[^`]*` \(hash: [^)]+\)",
    "// Generated by Wrangler by running `wrangler types` (hash: <normalized>)",
    text,
)
text = re.sub(
    r'import\("([^"]*src/index)"\)',
    'import("./src/index")',
    text,
)
print(text, end="")
PY
}

EXPECTED_NORMALIZED="$(normalize_types worker-configuration.d.ts)"
ACTUAL_NORMALIZED="$(normalize_types "$TMP_FILE")"

if [[ "$EXPECTED_NORMALIZED" != "$ACTUAL_NORMALIZED" ]]; then
  echo "[types-check] worker-configuration.d.ts is out of date."
  echo "[types-check] Run npm run cf:types --workspace @edgeintel/worker and commit the regenerated file."
  diff -u \
    <(printf '%s' "$EXPECTED_NORMALIZED") \
    <(printf '%s' "$ACTUAL_NORMALIZED") || true
  exit 1
fi

echo "[types-check] worker-configuration.d.ts is up to date."
